### ISSUE TITLE
Something About LSTM implementation

### ISSUE THREAD

**Issue by Penkace** [Zhikaiiii/traffic-prediction#3]
Hi! Your code inspires me a lot. Can you tell me how you implemented the LSTM module? Or is there any reference you can provide to me. I will appreciate it if you help me.
thx!

**Comment by Zhikaiiii** [comment]
Hello, it is an old code when I just started to learn Pytorch, and I implemented it based on the architecture of LSTM. In my advice, you can just use LSTM in Pytorch modules or try to read its source code if you want to implement it yourself.
